#!/usr/bin/env python3
# Copyright (c) 2026 ADBC Drivers Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Bulk-load Arrow data into Firebolt, including nested ARRAY and STRUCT columns.

Covers the four ingest modes and both APIs: the high-level
``Cursor.adbc_ingest`` and the low-level ``bind_stream`` + ``execute_update``
the wrapper is built on.

    python examples/python/bulk_ingest.py

Creates and drops tables named ``adbc_example_*``.
Configure with FIREBOLT_ADBC_DRIVER / FIREBOLT_URI — see examples/python/README.md.
"""

import argparse
import os

import adbc_driver_manager
import pyarrow as pa
from adbc_driver_manager import dbapi

DEFAULT_DRIVER = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "..", "..", "build", "libadbc_driver_firebolt.so"
)

TABLE = "adbc_example_events"
NESTED_TABLE = "adbc_example_nested"


def connection_settings() -> tuple[str, dict]:
    driver = os.environ.get("FIREBOLT_ADBC_DRIVER", DEFAULT_DRIVER)
    db_kwargs = {"uri": os.environ.get("FIREBOLT_URI", "http://localhost:3473")}
    if os.environ.get("FIREBOLT_DATABASE"):
        db_kwargs["adbc.firebolt.database"] = os.environ["FIREBOLT_DATABASE"]
    if os.environ.get("FIREBOLT_TOKEN"):
        db_kwargs["adbc.firebolt.token"] = os.environ["FIREBOLT_TOKEN"]
    return driver, db_kwargs


def show(cur, sql: str) -> None:
    cur.execute(sql)
    print(cur.fetch_arrow_table())


def flat_modes(cur) -> None:
    """The four ingest modes, on a flat schema."""
    first = pa.table({
        "id": pa.array([1, 2], pa.int32()),
        "name": pa.array(["alice", "bob"], pa.string()),
    })
    more = pa.table({
        "id": pa.array([3], pa.int32()),
        "name": pa.array(["carol"], pa.string()),
    })

    # create: CREATE TABLE from the Arrow schema, then INSERT.  Fails if the
    # table already exists.
    cur.execute(f"DROP TABLE IF EXISTS {TABLE}")
    cur.adbc_ingest(TABLE, first, mode="create")
    print(f"=== after create ({TABLE}) ===")
    show(cur, f"SELECT * FROM {TABLE} ORDER BY id")

    # append: INSERT into the existing table, schema untouched.
    cur.adbc_ingest(TABLE, more, mode="append")
    print("\n=== after append ===")
    show(cur, f"SELECT * FROM {TABLE} ORDER BY id")

    # create_append: CREATE TABLE IF NOT EXISTS, then INSERT — the idempotent
    # choice for a job that may be the first writer or the tenth.
    cur.adbc_ingest(TABLE, more, mode="create_append")
    print("\n=== after create_append (same row again) ===")
    show(cur, f"SELECT count(*) AS row_count FROM {TABLE}")

    # replace: DROP, CREATE, INSERT.  Everything previously in the table is gone.
    cur.adbc_ingest(TABLE, first, mode="replace")
    print("\n=== after replace ===")
    show(cur, f"SELECT * FROM {TABLE} ORDER BY id")

    cur.execute(f"DROP TABLE IF EXISTS {TABLE}")


def nested_types(cur) -> None:
    """ARRAY and STRUCT columns, with the DDL generated by the driver.

    The driver renders Arrow list types as ARRAY(...) and struct types as
    STRUCT("field" TYPE, ...), recursing to any depth, so nested data needs no
    hand-written DDL.
    """
    table = pa.table({
        "id": pa.array([1, 2], pa.int32()),
        "tags": pa.array([["red", "blue"], ["green"]], pa.list_(pa.string())),
        "author": pa.array(
            [{"name": "alice", "score": 10}, {"name": "bob", "score": 20}],
            pa.struct([("name", pa.string()), ("score", pa.int32())]),
        ),
        # A struct inside an array — both levels are generated.
        "revisions": pa.array(
            [[{"rev": 1}, {"rev": 2}], [{"rev": 1}]],
            pa.list_(pa.struct([("rev", pa.int32())])),
        ),
    })

    cur.adbc_ingest(NESTED_TABLE, table, mode="replace")
    print(f"\n=== nested types ({NESTED_TABLE}) ===")
    show(cur, f"SELECT * FROM {NESTED_TABLE} ORDER BY id")

    print("\ngenerated column types:")
    cur.execute(
        "SELECT column_name, data_type FROM information_schema.columns "
        f"WHERE table_name = '{NESTED_TABLE}' ORDER BY ordinal_position"
    )
    for column_name, data_type in cur.fetchall():
        print(f"  {column_name}: {data_type}")

    cur.execute(f"DROP TABLE IF EXISTS {NESTED_TABLE}")


def low_level_ingest(driver: str, db_kwargs: dict) -> None:
    """The same thing through the C-API objects.

    adbc_ingest() is a wrapper over exactly this: set the ingest options on a
    statement, bind an Arrow stream, execute_update().  Use it when you need to
    hand over a stream you are producing incrementally rather than a materialised
    table.
    """
    table = pa.table({"id": pa.array([7, 8, 9], pa.int32())})

    with adbc_driver_manager.AdbcDatabase(driver=driver, **db_kwargs) as db:
        with adbc_driver_manager.AdbcConnection(db) as conn:
            with adbc_driver_manager.AdbcStatement(conn) as stmt:
                stmt.set_options(**{
                    adbc_driver_manager.StatementOptions.INGEST_TARGET_TABLE.value: TABLE,
                    # The mode values have no enum in the driver manager; they
                    # are the literal option strings from the ADBC spec.
                    adbc_driver_manager.StatementOptions.INGEST_MODE.value: "adbc.ingest.mode.replace",
                })
                stmt.bind_stream(table.__arrow_c_stream__())
                stmt.execute_update()

            with adbc_driver_manager.AdbcStatement(conn) as stmt:
                stmt.set_sql_query(f"SELECT * FROM {TABLE} ORDER BY id")
                stream, _ = stmt.execute_query()
                print("\n=== low-level bind_stream + execute_update ===")
                print(pa.RecordBatchReader.from_stream(stream).read_all())

            with adbc_driver_manager.AdbcStatement(conn) as stmt:
                stmt.set_sql_query(f"DROP TABLE IF EXISTS {TABLE}")
                stmt.execute_update()


def main() -> None:
    argparse.ArgumentParser(description=__doc__.splitlines()[0]).parse_args()
    driver, db_kwargs = connection_settings()

    # autocommit=True so each ingest lands immediately and is visible to the
    # reads that follow.
    with dbapi.connect(driver=driver, db_kwargs=db_kwargs, autocommit=True) as conn:
        with conn.cursor() as cur:
            flat_modes(cur)
            nested_types(cur)

    low_level_ingest(driver, db_kwargs)


if __name__ == "__main__":
    main()
