---
name: enable-merge-to-main
on:
  pull_request:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: ./scripts/build.sh

      - name: Unit tests
        run: ./scripts/test-unit.sh

      - name: Integration tests
        run: ./scripts/test-integration.sh
